# Basic
title: Vno Jekyll
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 简单的描述
creator: ScottLaw

url: "https://scottlaw.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
  - {title: Projects, description: My Projects, url: 'https://scottlaw.github.io/project/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo:
    github:
    twitter:
    gplus:
    mail:

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
